export const ENGINE_EVENTS_ADD = 'ENGINE_EVENTS_ADD'
export const ENGINE_EVENTS_CLEAR = 'ENGINE_EVENTS_CLEAR'
export const ENGINE_DECODE_ARRAY_BUFFER_START =
  'ENGINE_DECODE_ARRAY_BUFFER_START'
export const ENGINE_DECODE_ARRAY_BUFFER_ERROR =
  'ENGINE_DECODE_ARRAY_BUFFER_ERROR'
export const ENGINE_DECODE_ARRAY_BUFFER_COMPLETE =
  'ENGINE_DECODE_ARRAY_BUFFER_COMPLETE'
