export const INSTRUMENT_ADD = 'INSTRUMENT_ADD'
export const INSTRUMENT_REMOVE = 'INSTRUMENT_REMOVE'
export const INSTRUMENT_UPDATE_PROPS = 'INSTRUMENT_UPDATE_PROPS'
export const INSTRUMENT_UPDATE_LABEL = 'INSTRUMENT_UPDATE_LABEL'
