export const AUDIO_EFFECT_ADD = 'AUDIO_EFFECT_ADD'
export const AUDIO_EFFECT_REMOVE = 'AUDIO_EFFECT_REMOVE'
export const AUDIO_EFFECT_UPDATE_PROPS = 'AUDIO_EFFECT_UPDATE_PROPS'
export const AUDIO_EFFECT_UPDATE_LABEL = 'AUDIO_EFFECT_UPDATE_LABEL'
