name: Test and lint

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup
      - uses: actions/setup-node@v6 # needed for oxlint
        with: { node-version: latest }
      - run: bun run test -- --coverage --silent
      - run: bun run lint
